name: Tests

on:
  push:
    branches: [ main, integration ]
  pull_request:
    branches: [ main, integration ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests and generate coverage report
      run: dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=lcov.info /p:ExcludeByFile=\"**/Parsing/Generated/*.cs\"

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: lcov.info
        flags: unittests
        fail_ci_if_error: true
        verbose: true
